Update workflow file to create proper image tag

diff --git a/.github/workflows/prod-build-and-push-docker-image.yml b/.github/workflows/prod-build-and-push-docker-image.yml
--- a/.github/workflows/prod-build-and-push-docker-image.yml
+++ b/.github/workflows/prod-build-and-push-docker-image.yml
@@ -26,11 +26,21 @@ jobs:
       run: echo ${{ secrets.AZURE_ACR_PASSWORD }} | docker login irisdevacr.azurecr.io -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin
 
     - name: Build and Push Docker Image
+      env:
+        GITHUB_SHA: ${{ github.sha }}  # Pass the commit SHA as an environment variable
       run: |
-        # Extract the first 7 characters of the commit SHA
-        SHORT_SHA="${GITHUB_SHA:0:7}"
-        IMAGE_TAG="prod-${SHORT_SHA}"
+        # Ensure the SHA is trimmed to the first 7 characters
+        SHORT_SHA=${GITHUB_SHA:0:7}
 
+        # Check if SHORT_SHA is not empty
+        if [ -z "$SHORT_SHA" ]; then
+          echo "Error: SHORT_SHA is empty"
+          exit 1
+        fi
+
+        # Construct the Docker image tag
+        IMAGE_TAG="prod-${SHORT_SHA}"
+        
         # Build and push the Docker image
         docker build -t irisdevacr.azurecr.io/exactech-superset:${{ env.IMAGE_TAG }} .
         docker push irisdevacr.azurecr.io/exactech-superset::${{ env.IMAGE_TAG }}
